sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*
  - SYMFONY_VERSION=2.6.*
  - SYMFONY_VERSION=2.7.*@dev
  - SYMFONY_VERSION=3.0.*@dev

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer self-update

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
  - composer install --prefer-source

script:
  - ./bin/phpunit --coverage-text

notifications:
  email:
    - thomas@tourlourat.com
